apiVersion: apps/v1
kind: Deployment
metadata:
  name: caption-craft-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caption-craft-backend
  template:
    metadata:
      labels:
        app: caption-craft-backend
    spec:
      containers:
      - name: caption-craft-backend
        image: saideepsamineni/caption-craft:backend-image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # env:
        # - name: MONGODB_URI
        #   value: "mongodb+srv://caption-craft:R7MOIUbb43y7TJkv@cluster-craft.conjprb.mongodb.net/"
        # - name: MONGODB_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-secret
        #       key: username
        # - name: MONGODB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-secret
        #       key: password
