apiVersion: apps/v1
kind: Deployment
metadata:
  name: caption-craft-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caption-craft-frontend
  template:
    metadata:
      labels:
        app: caption-craft-frontend
    spec:
      containers:
      - name: caption-craft-frontend
        image: saideepsamineni/caption-craft:frontend-image
        imagePullPolicy: Always
        ports:
        - containerPort: 80